### ISSUE TITLE
ReferenceError: HAR is not defined

### ISSUE THREAD

**Issue by JosephCastro** [firebug/har-export-trigger#1]
Hi
First, thanks for this plugin, it will be a really helpful.

Trying to execute (follow the readme) I get this error ReferenceError: HAR is not defined and I can't figure out what is wrong.

Thanks again

**Comment by janodvarko** [comment]
Are you using Firefox Nightly?

Honza

**Comment by JosephCastro** [comment]
I'm using Firefox 35 - 39  
D:
I get errors using Nightly with selenium

**Comment by janodvarko** [comment]
The extension requires Firefox 42+

There is a patch included in 42 that's needed by this extension

See more:
https://bugzilla.mozilla.org/show_bug.cgi?id=1184889

Honza

**Comment by JosephCastro** [comment]
I using Firefox Dev Edition 42.0a2, but I get other kinds of errors like, problems to load the profile, to install unsigned extensions, but nothing related to this extension.

It's seem to be a problem with selenium because is a new version of FF.

In the other hand I tested manually and I get the same problem: HAR is not defined

**Comment by janodvarko** [comment]
Thanks for the feedback!

I released new version (beta 3)
https://github.com/firebug/har-export-trigger/releases
- It's uploaded on AMO, but awaiting preliminary review, so you might still use
  the following pref to disabled the signing check:

xpinstall.signatures.required

I've been carefully testing with Nightly and DevEdition and works for me

Here is a test page:
http://janodvarko.cz/har/tests/har-export-trigger/har-export-api.html

Does it work for you?

Honza

**Comment by JosephCastro** [comment]
Nice!
Works fine!!
Thanks you.

**Comment by janodvarko** [comment]
Excellent, thanks for the feedback

Honza
