### ISSUE TITLE
Question: Clarifying which Developer Toolbox you mean on the blog page

### ISSUE THREAD

**Issue by PenelopeFudd** [firebug/har-export-trigger#17]
Hi;

On the page http://www.softwareishard.com/blog/har-export-trigger/ , it says:

> Basic automated HAR export is already supported by Firefox 41+ and all the user needs to do is set devtools.netmonitor.har.enableAutoExportToFile preference to enable it. As soon as this pref is true, a new HAR file is created automatically for every loaded page and stored in <your-firefox-profile-dir>/har/logs directory.
> 
> The developer Toolbox needs to be opened for this built-in feature to work.
> 
> Note that manual HAR export is also supported since Firefox 41. Just select the Network panel (make sure there are some collected data) and pick either Copy All As HAR (into the clipboard) or Save All As HAR (into a file).

I'm trying to get the native FF 43.0 har exporting to work, and have set devtools.netmonitor.har.enableAutoExportToFile to true, but the .../har/logs directory hasn't been created.

Can you give a link or description to which developer toolbox needs to be opened, or how to open it?  If I search Google for it, it suggests "Developer Toolbar", which I've already got.  I'm going a little batty trying to find this mysterious developer toolbox in the menus.  The only network panel I can find is in Firebug, but that's not what you meant, as it's definitely open, but not logging.  And the "Copy/Save All As HAR' option is not on the menu.

Anyhoo, thanks for listening to a newbie.

**Comment by janodvarko** [comment]
Developer Toolbox:
https://developer.mozilla.org/en-US/docs/Tools/Tools_Toolbox

I've also update the page.

Honza
