### ISSUE TITLE
Promise for triggerExport is not coming back

### ISSUE THREAD

**Issue by ghost** [firebug/har-export-trigger#18]
Hey,
I'm using this HAR plugin among with firefox add-on that is related to it.

when activating triggerExport with two then functions (as success and failure) mixed with my code the promise are not going into the success nether the error function (like he enters pending status).

The strange thing that when I execute it in the console directly at any time it's performing well!!

What could happened?!

**Comment by ghost** [comment]
Unfortunately, the issue didn't resolved. I've tried even the latest build .10, and even gone further to compile the code manually on my own PC.

The problem can be resolved by putting break point before HAR.triggerExport function and removing the breakpoint and press F8! Sound very strange!!

**Comment by ghost** [comment]
I'm running it from an YouTube Player event cycle! Can this affect the scope? and what may be the solution of that?

**Comment by xmhubj** [comment]
It has been resolved by Csaba! But the fix is not included in the xpi package.

**Comment by meskadam** [comment]
I'm also hitting this issue. When can the fix be released in xpi package?

**Comment by ghost** [comment]
I noticed that with older Firefox (45) it's working or even older than that. I'm not sure

**Comment by meskadam** [comment]
I am using Firefox 46. I tried downloading the code from github and building it, but the build hangs. Will appreciate if new build of the plugin is released!
