### ISSUE TITLE
HAR export trigger + Selenium + Marionette

### ISSUE THREAD

**Issue by soulgalore** [firebug/har-export-trigger#30]
Has anyone got the trigger working with Selenium and Marionette (Geckodriver) for Firefox 47?

With Firefox 46 + Selenium everything worked just fine for us, but we haven't started using the Geckodriver so we where caught off guard with the release of 47. 

We use Selenium NodeJS version and I started by setting the Firefox options to use marionette, downloaded the latest version of Geckodriver (0.8.0) and started to test. In Selenium Nodejs, you need to explicitly set the binary to Firefox 47 (using marionette defaults to  Firefox Developer Edition).

To fetch the HAR we do like this:
https://github.com/tobli/browsertime/blob/1.0/lib/core/engineDelegate/firefoxDelegate.js#L36-L57

If I use FF 47 (and 46) with Marionette the scripts timeouts in Selenium. In 46 not using Marionette you could set the setScriptTimeout but that doesn't work with Marionette https://github.com/mozilla/geckodriver/issues/77.

The har-api-ready event never kicks in for me. But could it be with the installation of the extension?

So has someone else tested the trigger with 47 and Marionette?

Best
Peter

**Comment by brtsay** [comment]
Hi Peter,

Don't know if this is helpful or not, but I have gotten the trigger working using 
Firefox 47 
Selenium 2.53,
Geckodriver 0.9.0 + Marionette
Python 3.5.2

To use HAR export trigger, I download the .xpi from Firefox Add-ons and added it to a Firefox profile via add_extension.

**Comment by soulgalore** [comment]
Hey @brtsay 
thanks, so the event fires for you? I'll try again with updated versions tonight then.

Best
Peter

**Comment by brtsay** [comment]
Hi Peter,

Yes, I believe so. To be honest, I'm a complete newbie with this kind of stuff. I have it set up to auto export the HAR file, which it does successfully.

EDIT: Actually, while auto export works, the har-api-ready event does not seem to kick in for me either.

**Comment by soulgalore** [comment]
Finally got this working. The problem was that with Selenium 2.53.x (javascript version) the HAR export plugin wasn't installed using Geckodriver (using the same code as for previous version of Firefoxdriver). Upgrading to latest beta version of 3 and Geckodriver 0.10.0 made it work.

**Comment by crackoner** [comment]
Hi Soulgalore,
Could you share your Selenium + har-export-trigger example?  I'm able to use the HAR-export-trigger module manually in a firefox console, but when I run it in my nodejs selenium script it says "HAR not defined".

I believe the issue might be caused because I'm not pointing to the firefox browser instance that selenium creates.  But I'm not sure.
     
```
var webdriver = require('/usr/local/lib/node_modules/selenium-webdriver'),
    By = webdriver.By,
    until = webdriver.until;

//open instances browser
var driver = new webdriver.Builder().
    forBrowser('firefox').
    build();

var options = {
  token: "test",      // Value of the token in your preferences
  getData: true,      // True if you want to get HAR data as a string
};

driver.get('https://github.com');

HAR.triggerExport(options).then(result => {
  console.log(result.data);
});
```
Thanks,
Mike

**Comment by soulgalore** [comment]
Hi @crackoner 

here you can check the JavaScript we run (to get the HAR): https://github.com/sitespeedio/browsertime/blob/master/lib/core/engineDelegate/firefoxDelegate.js

And here we install the plugin:
https://github.com/sitespeedio/browsertime/blob/master/lib/core/webdriver/firefox.js#L228-L236

Best
Peter
