### ISSUE TITLE
HAR.triggerExport() exports requests who are still w8ing for response

### ISSUE THREAD

**Issue by Glavic** [firebug/har-export-trigger#34]
I have javascript script, that stores all HAR's to file:

```
var dump_i = 0;

function dump() {
  var options = {
    token: "test",
    fileName: "prefix-" + Date.now() + "-" + dump_i
  };
  dump_i++;

  HAR.triggerExport(options).then(result => {
    HAR.clear({token: options.token});
  });
}

setInterval(dump, 1000);
```

Problem here is, that HAR is saved (and then cleared) even if response is still not available.
How can I save only HAR's than have full response?

**Comment by soulgalore** [comment]
@Glavic checkout https://github.com/firebug/har-export-trigger/wiki/Examples#har-api-ready

**Comment by Glavic** [comment]
@soulgalore I already read all the documentation on this repository. It is not that HAR API is not available; it is. HAR files are saved every second (see `setInterval(dump, 1000);` at the end). Problem is, that some files are saved without response, and  that is because `HAR.triggerExport()` is triggered after request is made, and before response is returned. And because I run `HAR.clear()` after every export, HAR that was partially exported is not available in next loop.
