### ISSUE TITLE
Returning object from triggerExport

### ISSUE THREAD

**Issue by raicabogdan** [firebug/har-export-trigger#4]
Hello Honza,

I was able to make this working in the end in my browser. I only had to restart the browser after installing har-export-trigger.

Anyway, the issue currently is that I want to return the har.log object back to selenium, I don't want to have lots of files created, rather, I want get the data, parse it and dump it. `har-export-trigger` is really the best I've tested so far and its really fast.

I'm currently lost at this step. If possible, please provide some pointers in which direction to go.

To explain the issue, as you know:
`HAR.triggerExport(options);`
this returns a promise, I played a bit with it but I can't figure out a way to get the `har.log` object outside that scope.

I guess it was not intended to be used like that? Is there any workaround?

Thank you again.

**Comment by janodvarko** [comment]
Set this pref to true to enable automation:
`extensions.netmonitor.har.enableAutomation`
(no file will be created)

This pref should specify the token (string) that you'll pass to API calls:
`extensions.netmonitor.har.contentAPIToken`
(e.g. `mySpecialValue`)

The following code triggers HAR export. No file created, HAR log returned in the callback:

```
var options = {
  token: "mySpecialValue",
  getData: true,
  title: "Title for the HAR log",
  jsonp: false,
};

HAR.triggerExport(options).then(result => {
  var har = JSON.parse(result.data);
  console.log("HAR log: ", har.log);
}, err => {
  console.error(err);
});
```

Note that the developer Toolbox needs to be opened (press F12). But do _not_ select the Network panel by default, it could slow down the page load a bit and influence the timing results.

Does that work for you?

Honza

**Comment by raicabogdan** [comment]
It works fine when using firefox opened manually by me and running the simple code:

```
HAR.triggerExport({token: "test", getData: true}).then(result => {
  var har = JSON.parse(result.data);
  console.log("HAR log: ", har.log);
}, err => {
  console.error(err);
});
```

It returns just fine.

However if I start the script using selenium in python, it does not show anything in error log. And if I attempt to run it manually in the window opened by selenium, it only gets me with
`Promise { <state>: "pending" }`

This leads me to think something needs to be set in my selenium script to run as expected.

However further testing this, I removed / changed the token to be wrong on purpose, the console.log was immediately called

`Security check didn't pass. You need to set 'extensions.netmonitor.har.contentAPIToken' pref to match the string token passed into HAR object API call (browser restart is required)  line 69 > Function:1:169
anonymous/<()`

What do you think is the cause for this specific pattern?

In python I only use:

```
profile.set_preference("extensions.netmonitor.har.contentAPIToken", "test");
profile.set_preference("devtools.netmonitor.har.enableAutoExportToFile", False);
```

So it returns ok on error, but not on complete.

Bogdan

**Comment by janodvarko** [comment]
> profile.set_preference("extensions.netmonitor.har.contentAPIToken", "test");
> profile.set_preference("devtools.netmonitor.har.enableAutoExportToFile", False);

You should do:

```
profile.set_preference("extensions.netmonitor.har.contentAPIToken", "test");
profile.set_preference("extensions.netmonitor.har.enableAutomation", true);
```

Either `enableAutoExportToFile` or `enableAutomation` must be true to enable automated collecting of HTTP data. The difference is that `enableAutoExportToFile` auto-creates *.har file log while `enableAutomation` does not.

Honza

**Comment by raicabogdan** [comment]
I think it works! That setting seems to have been the issue. Testing and will report in a few minutes.

**Comment by raicabogdan** [comment]
Test completed and works as expected. Thank you again for the help! :+1:

**Comment by janodvarko** [comment]
Excellent!

Honza
