### ISSUE TITLE
HAR is not defined

### ISSUE THREAD

**Issue by crackoner** [firebug/har-export-trigger#46]
Hi,
I feel like this has been answered several times already, but none of the threads I looked at solved my issue.

I'm running Firefox 53.0.2 on OSX and have the HAR Export Trigger 0.5.0-beta.7 add-on installed.

The following Firefox settings are set:

  devtools.netmonitor.har.enableAutoExportToFile => true
  extensions.netmonitor.har.contentAPIToken => test
  extensions.netmonitor.har.enableAutomation => true
  extensions.netmonitor.har.autoConnect => true

The result is I'm not able to see the HAR object, and get the "ReferenceError: HAR is not defined" message in console.

I've tried the test page:
  http://janodvarko.cz/har/tests/har-export-trigger/har-export-api.html

And the "Use HAR API" buttons all return "HAR is not defined" in console.

I've been attempting to get this working for several days now, and not making any progress.  Would appreciate any advice.

Thanks in advance

**Comment by soulgalore** [comment]
Hi @crackoner 
start with upgrade to beta-10 and see if that helps: https://github.com/firebug/har-export-trigger/issues/37#issuecomment-249037171

Best
Peter

**Comment by soulgalore** [comment]
Hmm it seems like only beta-7 is available at addons. You can download a signed beta-10 from https://github.com/sitespeedio/browsertime/tree/master/vendor

**Comment by crackoner** [comment]
Hi Soulgalore,
Thanks for the quick reply.  The beta-10 version fixed the issue!  I'm able to see the HAR object now.  Looking forward to trying this out!

Thanks again
