### ISSUE TITLE
Missing pageTimings

### ISSUE THREAD

**Issue by raicabogdan** [firebug/har-export-trigger#5]
Hello,

Second issue which I thought I should create separately, is regarding the data collected, the `pages.pageTimings` has the values

```
    "pages": [
      {
        "startedDateTime": "2015-09-15T23:49:33.457+03:00",
        "id": "page_10",
        "title": "my custom title",
        "pageTimings": {
          "onContentLoad": -1,
          "onLoad": -1
        }
      }
```

Was this a 'todo' thing  or is there a meaning for this and I missed it?

Thank you.

**Comment by janodvarko** [comment]
This is a platform issue, `onContentLoaded` and `onLoad` timings are not available.
But, totally agree, this should be fixed!

Please file bugzilla report
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Developer%20Tools%3A%20Netmonitor
(search before, not sure if this has been already reported)

Edit: please cross post the bugzilla report link here

Honza

**Comment by raicabogdan** [comment]
Seems there's already a bug report there:
https://bugzilla.mozilla.org/show_bug.cgi?id=1174091

Thanks !

**Comment by EliSnow** [comment]
Couldn't this be fetched from `performance.timing`?

**Comment by raicabogdan** [comment]
The purpose for a HAR generation script is to collect a well made HAR file format. Leaving the two values out is no longer a complete HAR format. Of course, what is doing now its using `-1` but that's a value that its incorrect. And using `performance.timing`, that's what I'm doing actually, but a bug in the script is a bug, and was reported.

**Comment by janodvarko** [comment]
Using `performance.timing` sounds like a great idea. I'll investigate it...

Honza

**Comment by nileshr** [comment]
Is there any workaround I can use for now to get these pageTiming values?

**Comment by janodvarko** [comment]
The following script might help you.

Honza

```
  var options = {
    token: "test",
    getData: true,
  };

  HAR.triggerExport(options).then(result => {
    var har = JSON.parse(result.data);
    var t = performance.timing;
    var pageTimings = har.log.pages[0].pageTimings;
    pageTimings.onContentLoad = t.domContentLoadedEventStart - t.navigationStart;
    pageTimings.onLoad = t.loadEventStart - t.navigationStart;

    console.log("HAR log (" + result.data.length + ") ", har.log);
  }, err => {
    console.error(err);
  });
```

**Comment by nileshr** [comment]
Thanks!

**Comment by talwararjun4** [comment]
@janodvarko
Is there any update on this?  is this fixed ?
