### ISSUE TITLE
Compatibility issues with Firefox 55?

### ISSUE THREAD

**Issue by soulgalore** [firebug/har-export-trigger#53]
We tried to upgrade from FF 54 to 55 yesterday and all tests fail on 55 because it seems like the HAR export trigger callback never happens (it times out). I've tested on https://www.sitespeed.io and https://www.wikipedia.org/ and got the same result.

**Comment by stephendonner** [comment]
Apologies if this isn't helpful/already known..

Not sure about the callback, but using http://janodvarko.cz/har/tests/har-export-trigger/har-export-api.html with https://addons.mozilla.org/firefox/downloads/file/449485/har_export_trigger-0.5.0-beta.10-fx.xpi on Build identifier: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:55.0) Gecko/20100101 Firefox/55.0, I get the following:

22:53:54.414 ReferenceError: HAR is not defined 1 har-export-api.js:40:3
	onExecuteExport http://janodvarko.cz/har/tests/har-export-trigger/har-export-api.js:40:3
	onclick http://janodvarko.cz/har/tests/har-export-trigger/har-export-api.html:1:1

There's also pre-existing https://github.com/firebug/har-export-trigger/issues/49

@janodvarko would you or someone else be able to help, here?  I'd like to use @soulgalore's sitespeed.io Docker image to help performance-test the AMO rewrite in Q3/Q4; thanks!

**Comment by stephendonner** [comment]
@soulgalore not to speak for him, but to speed up the flow of information, I've just confirmed with Jan in #devtools that "the extension needs to be transformed into a WebExtension, first" - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on

**Comment by soulgalore** [comment]
It started with 55, it worked in 54 I know that for sure. I had a go to start to debug (using FF 56 developer since there's no way to run unsigned without using dev version right) and I can see that I get the same error. There's some empty try/catches that swallow errors and I could see one of them failing (=get one error) but I'm not sure how it used to work like (maybe the swallowed error where there before too). I cannot try on latest FF stables since you cannot run unsigned extension in stable. Is it better to rollback to an really old version or should I use an unbranded version? 

For the new version, yes I know it needs to be a WebExtension :) It will be doable when there's support for getHAR https://bugzilla.mozilla.org/show_bug.cgi?id=1311177 but I will still have the problem that devtools needs to be open. As I see it I need help from Mozillians to implement the getHar method, do a hack to get it without devtools open (or visible) and then we can create the plugin used by Selenium etc that can replace HARExportTrigger.

**Comment by stephendonner** [comment]
@digitarald: is there anyone you know who could take a look at this a bit more in-depth/try to scope out work?  Thanks!

**Comment by soulgalore** [comment]
Another way could be to do what [WebPageTest do](https://github.com/WPO-Foundation/wptagent/blob/master/internal/support/firefox_log_parser.py), parsing the moz log and make a HAR of that, but then every flavor of Selenium needs to have it own hack to generate and make the HAR available.

**Comment by digitarald** [comment]
@janodvarko we talked about that in the past, automation around HAR. What are your thoughts on workaround?

**Comment by janodvarko** [comment]
@digitarald one option is using auto-export. All you need is to set `devtools.netmonitor.har.enableAutoExportToFile` to `true` (about:config)

This option doesn't offer such flexibility as exporting the `HAR` API into the page, but provides a way how to automate things.

I'd like to put support for HAR on the list of things for Q4, let's discuss next week.

Honza

**Comment by soulgalore** [comment]
@digitarald @janodvarko did you have time to talk about exporting the HAR, is it anyway I could help?

**Comment by digitarald** [comment]
@soulgalore did you check out the pref @janodvarko mentioned? It has some control over where the file is stored as well.

To have a solution medium-term we are in the process of defining the scope of work for Q4 for import/export in the Netmonitor UI. It would help to understand the flow you have for Firefox and/or other tools right now as a user story:

- How did you so far export HAR files from different browsers?
- How do you view HAR files and what are the most important that you are looking for?
- How do you compare HAR files between runs?
- What are the painpoints in the whole process and how would the perfect process work like?

Thanks a lot in advance for helping us!

**Comment by soulgalore** [comment]
@digitarald I think @janodvarko meant it is the solution to do that in 57 when we can hack a WebExtension? The current versions don't work in 55/56 and it doesn't matter if you try to get it through JS or write to disk. I tried to debug and could see that there's a try/catch that swallows an error, but I'm having a hard to rollback to older FF to see if that was the case before too. WebExtensions will be so much easier for outsiders to debug :)

>How did you so far export HAR files from different browsers?

In Firefox we use the HAR export trigger in Browsertime/sitespeed.io. For Chrome we parse the Chrome trace log with https://github.com/sitespeedio/chrome-har, doing like that we actually get a better HAR than exporting directly from Chrome. WebPageTest [parses](https://github.com/WPO-Foundation/wptagent/blob/master/internal/support/firefox_log_parser.py) the MOZ log and that is ok, but I think(?) the MOZ log misses things and so far the HAR directly from the har-export-trigger is better (and of course less work). I like the idea of providing the same HAR as you get within the browser (as long as it is good).

> How do you view HAR files and what are the most important that you are looking for?

We use [PerfCascade](https://github.com/micmro/PerfCascade), the reason is that it is nice and easy to hack. You know the HAR format is old (but you done a fantastic job with it @janodvarko !), so both Browsertime and WebPageTest adds extra fields to it starting with a  _. For example we both add info if an asset was HTTP2 PUSHED (that doesn't exists in the old HAR spec). Michael (who is the creator of PerfCascade) has a fix for showing that directly in waterfall. It would be super cool if Firefox also "extended" the HAR spec add added extra field until there's a new version :) We also use [PageXray](https://github.com/sitespeedio/pagexray) that takes a HAR file and converts it to a more human readable/understandable format. Like a summary of the page.  When I look at the HAR, the most important thing is knowing the order of the assets, easy to see what kind of asset it is, and to correlate the download of assets and the different timing metrics, checkout the image:
<img width="998" alt="screen shot 2017-09-15 at 10 23 38 am" src="https://user-images.githubusercontent.com/540757/30473242-044b5b36-9a00-11e7-81f3-cd95b6038c28.png">
so we can correlate changes in the metrics with downloaded assets etc.

> How do you compare HAR files between runs?

I'm glad you asked that :D Both at Wikimedia and in sitespeed.io we send the timing metric to Graphite (or other time/data storage). Then when we spot a change or gets an alert from Grafana we compare the HARs. If we use WebPageTest we compare with the built in functionality in WPT. Else I use the new https://compare.sitespeed.io/ where you drag/drop the HARs thar makes it a little easier to spot changes in the page. Both have the slider to slide between different HARs, that's the best way I've seen to compare HARs. For compare.sitespeed.io we also use PageXray to get out some extra metrics (like total page size etc) so it's easier to actually see what changed.

> What are the painpoints in the whole process and how would the perfect process work like?

We use webdriver/Selenium to drive Firefox and the whole Geckodriver switch has been the worst experience. Like Firefox/Gecko/exporting the HAR has been not in sync(broken) so you need to use old Firefox version. It works fine in Docker since we lock the version until we know the new version works, but for people running on there local desktop without Docker, it has stopped working so many time so I've lost count.

If we can just get the HAR file written to disk that would great (configurable name and where) and than make sure the HAR follows the spec as much as possible and maybe add some extra field. Today for for example the HAR from Firefox miss [page timings](http://www.softwareishard.com/blog/har-12-spec/#pageTimings) so we add that ourself. 

One last thing: We record a video of the screen so it's important that all panels etc is closed.

Ping me on IRC if you have time to talk, I would love to help out when you start the project :)

**Comment by fmrahman** [comment]
@janodvarko First of all thanks very much for providing the wonderful har-export plugin which exactly matches our requirements. We have been using this plugin for the last one year and the experience is very cool.

But with this new Firefox changes using gecko driver and selenium webdriver 3.x, the har-export trigger is not working. HAR file could not be dumped with Firefox 55.0 and selenium-server-standalone-3.5.3.jar. 

I know you guys already been informed of this issue but I would like to convey that our team is also impacted by this problem. We are stuck now, without HAR we can't get the metrics. For our cloud customers, we are using Docker so there is no problem for firefox upgrade but for on-premise customers, there is a pressure to upgrade the firefox versions.

My humble request is to resolve the issue at the earliest and save our customers. :)

thanks.

**Comment by janodvarko** [comment]
Hi, thanks, I am glad the extension works for you!
I am working on new version based on new WebExtension API introduced in Firefox. It should be ready in (just starting) Q4 2017.

Jan Honza  Odvarko

**Comment by janodvarko** [comment]
Just for the record, the new WebExtension is available here:
https://github.com/devtools-html/har-export-trigger

Honza
