### ISSUE TITLE
high `connecting` value in har file

### ISSUE THREAD

**Issue by raicabogdan** [firebug/har-export-trigger#6]
Hello Honza,

This is probably again not an issue with the extension, but pointing out as it was really noticeable with a site of mine that has lots of resources served through Cloudflare.

As you may know, browser can re-use TCP connection, especially if keep-alive is enabled and honored. Again this may be a bug with the browser or maybe a setting in the browser that I need set, but I strongly believe that the dev. version of firefox doesn't re-uses TCP connection.

I'll provide a screenshot from two HAR files, one (on the left) exported using Firefox 42 and another one (on the right) exported using Firefox 40 with netexport.

![har_difference](https://cloud.githubusercontent.com/assets/4399340/9916910/87570066-5cc7-11e5-8349-dced53aa3724.png)

The image show only the first top resources. Going downwards, this keeps on _increasing_ which is also strange ...

Also, checking the response header for the httpVersion, I see `httpVersion: HTTP/1.1` however again, tcp connection is not being re-used and the har file has 

```
blocked 0
dns 0
connect 26
send 0
wait 68
receive 0
```

Do you think its best to fill a bug with firefox directly or is this maybe normal ?

Bogdan

**Comment by janodvarko** [comment]
Interesting...

You might want to check the following prefs in your configs:

network.http.max-connections
network.http.max-persistent-connections-per-proxy
network.http.max-persistent-connections-per-server

Also, did you have e10s enabled/disabled for both?

Btw. the screenshot comes from a HAR diff tool or it's just manually created?
(it looks good)

Otherwise yes, the best is to file a bugzilla bug (and cross post the link to the bug here)

Thanks
Honza

**Comment by raicabogdan** [comment]
The specific prefs are identical.

It does seem like enabling e10s helps. At least when looking at the network, it does appear to show properly now.

I'll test in a moment in selenium.

The screenshot is manually made (have a big screen).

LE: Do you know the prefs related to e10s ? I only found:

```
profile.set_preference("browser.displayedE10SNotice", 4);
profile.set_preference("browser.displayedE10SPrompt.1", 5);
```

but don't appear to be working with selenium.

Thanks

**Comment by raicabogdan** [comment]
Hello again,

It seems like you can enable it using: `browser.tabs.remote` pref. But once its enabled, if you enable the web console in one page, and navigate to another website, the dev console closes, thus the plugin no longer works. (This is while using selenium).

Is there a way to keep the dev console active / enabled on all sites?

Thank you.

**Comment by janodvarko** [comment]
I don't see this behavior.
The pref for enabling e10s  should be:  `browser.tabs.remote.autostart.2`

When I open the toolbox, select the Console panel and navigate the current tab to different location, the Toolbox stays open and the Console panel selected.

Honza

**Comment by raicabogdan** [comment]
That's when using the browser manually. If you open it using selenium you'll find the Toolbox closing. Which is really frustrating.
1. If you don't use `browser.tabs.remote.autostart`, python with selenium works well, but causes the high connection time you see above.
2. if you do use `browser.tabs.remote.autostart`, python with selenium works when opening url, closes the previously open toolbox (I open toolbox first, then navigate to the page I want), thus the extension doesn't work anymore.

Its frustrating to be honest :(

**Comment by janodvarko** [comment]
It's weird, why the behavior would be different when used with Selenium?

What if you open the Toolbox again (by synthesizing F12 key press)?

Honza

**Comment by raicabogdan** [comment]
I tried running the ActionsChain again after `webdriver.get(url);` but not working, rather I believe its not even being triggered. So I made another specific test case:

```
    print "before get";
    browser.get(url);
    print "after get";
```

If not using e10s, I get:

```
~$ python firefox.py
before get
after get
Data completed!
```

but when using e10s, I get only:

```
~$ python firefox.py
before get
```

and then just hangs. So something is happening with selenium not being able to understand multi-process tabs ?

So I thought of seaching a 'specific' selenium e10s keyword on google, got me here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1089938

and it seems I've hit this exact bug :( booooo

**Comment by raicabogdan** [comment]
Doesn't appear like I'll have any solution to this any time soon...

Do you think its possible to use netexport to trigger it from javascript instead for the har generation? I think that would be my only solution at this point :(

**Comment by janodvarko** [comment]
You can try NexExport, note that it needs Firebug 2.*
(but it hasn't been maintained for long time)

Hope that bug will be fixed soon!

Honza

**Comment by raicabogdan** [comment]
Thanks, will try. It can't get any worse than this ... hopefully not asking too much :(

**Comment by janodvarko** [comment]
> hopefully not asking too much :(

No problem!
Honza

**Comment by raicabogdan** [comment]
Right, the meaning of 'it hasn't been maintained for long time' is very strong. Can't work with it unfortunately. However it seems pipeling in Firefox helps and I can use this extension.

Closing this issue as it does appear to be a browser thing in the end so no point keeping an issue here.

Thanks for your time on this issue.

**Comment by janodvarko** [comment]
Cool, thanks for the update.

Honza
