### ISSUE TITLE
wrong response.content.mimeType in har

### ISSUE THREAD

**Issue by raicabogdan** [firebug/har-export-trigger#7]
Hello Honza,

There's a bug I found in my project and after checking it more, it seems the extension doesn't properly sets the mimeType in the response header.

I checked with "copy all as Har" and using the extension, the responses from the two is really different.

For example for the main request, the html file, you always get `text/plain`.

![wrong_mime_type](https://cloud.githubusercontent.com/assets/4399340/9977495/ee4c15d4-5f12-11e5-854b-0495ae9f41f6.png)

Let me know if you need more details. Later I can try to see if I can help in fixing this.

Bogdan

**Comment by raicabogdan** [comment]
I found the cause. Its again in the platform, in the `har-collector.js` file

```
  onResponseContent: function(response) {
    let file = this.getFile(response.from);
    file.mimeType = "text/plain";
    file.responseContent = response;

    // Resolve long string
    let text = response.content.text;
    if (typeof text == "object") {
      this.getString(text).then(value => {
        response.content.text = value;
      })
    }
  },
```

Someone just set it to `text/plain` specifically to each response. I'm not entirely sure why. I've confirmed that that's the cause. Do I need to submit a bugzilla bug for this?

At this point I'm using a self-compiled aurora build and works alright for me.

**Comment by janodvarko** [comment]
Ah, that's actually my mistake.

I created a bug report here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1206618

So, if I remove the following line it works  for me
file.mimeType = "text/plain";

Or did you make any other modification?

Honza

**Comment by raicabogdan** [comment]
I added the following:

`file.mimeType = response.content.mimeType`

and it seems to work fine for me. To be honest I was lazy to test it fully, I was thinking since you are giving to `file.responseContent` the entire `response`, that it should be enough, but I didn't knew where else was the `file.*` object being used so I just altered it to include the `mimeType` also.

I think you should know better than me at this point. Thanks for reviewing this.

**Comment by janodvarko** [comment]
The
https://bugzilla.mozilla.org/show_bug.cgi?id=1206618

landed, so I am closing this report

Honza
