### ISSUE TITLE
Cannot get it to work with selenium with java

### ISSUE THREAD

**Issue by joshhe** [firebug/har-export-trigger#8]
Hi 

I don't know what I did wrong. 
I am using firefox 42.0b9 with HAR Export Trigger 0.5.0-beta.6. Here is code I used.

FirefoxProfile profile = new FirefoxProfile();
    profile.setPreference("devtools.netmonitor.har.enableAutoExportToFile", true);
    profile.setPreference("devtools.netmonitor.har.pageLoadedTimeout", 10000);
    profile.setPreference("app.update.enabled", false);
    System.out.println("Profile directory:" + profile.layoutOnDisk() + ".");
    String suggestedProfile = System.getProperty("webdriver.firefox.profile");
    System.out.println("Profile name:" + suggestedProfile);
    WebDriver driver = new FirefoxDriver(profile);
    Thread.sleep(5000);
    Actions action = new Actions(driver);
    //Do I need this? 
    action.sendKeys(Keys.F12);
    action.perform();
    Thread.sleep(10000);
    driver.get("http://google.com");
    driver.quit();
    Thread.sleep(100000);

But I don't see any har file in the profile directory. Am I doing something wrong? 
Thanks!

**Comment by joshhe** [comment]
Oops, looks like I need profile.addExtension(new File(extension)); I thought I don't need it if I install them manually. Once I have it in my code, it works! This tool is great! It made the waterfall automation so much easier!! Thanks!

**Comment by janodvarko** [comment]
Awesome!

Honza
